name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Find component directory
        id: find_component_dir
        run: echo "COMPONENT_DIR=$(find . -type d -name 'META-INF' -exec dirname {} \;)" >> $GITHUB_ENV
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run make_release

      - name: Make Release Artifact
        run: npm run make_release

      - name: Extract version number
        uses: nyaa8/package-version@v1.0.3
        with:
         path: ${{ env.COMPONENT_DIR }}/package.json

      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
  
      - name: Check if release exists and is prerelease
        id: check_release
        run: |
          if gh release view "_${{ env.BRANCH_NAME }}" --json isPrerelease --jq '.isPrerelease'; then
            echo "release_exists=true" >> $GITHUB_ENV
          else
            echo "release_exists=false" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Delete Prerelease release & Tag
        if: env.release_exists == 'true'
        run: |
            gh release delete _${{ env.BRANCH_NAME }} --cleanup-tag --yes
            while git fetch --tags --prune-tags; git tag -l | grep _${{ env.BRANCH_NAME }}; do
                sleep 2;
                printf "still waiting...\n"
            done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Create release
        run: |
          gh release create "_${{ github.ref_name }}" --target "${{ env.BRANCH_NAME }}" --prerelease --title "Nighlty Build ${{ env.BRANCH_NAME }}" --notes "Nightly build. Branch: ${{ env.BRANCH_NAME }} Commit: ${{ github.sha }} Package Version: ${{ env.PACKAGE_VERSION }}"
          echo "release_exists=true" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload assets
        if: env.release_exists == 'true'
        run: |
          gh release upload "_${{ env.BRANCH_NAME }}" ${{ env.COMPONENT_DIR }}/*.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
